<h1>NIGERIA</h1>
		<img src="Nigeria/Flag_of_Nigeria.png" style="height: 200px">
		<p>Le ​<b>Nigeria</b>​, parfois orthographié ​<b>Nigéria</b>​, sous sa forme longue <b>​république fédérale du Nigeria</b>​, en anglais <i>​Federal Republic of Nigeria</i>, est un pays d'​<a href="https://fr.wikipedia.org/wiki/Afrique_de_l%27Ouest" style="color:darkorchid">Afrique de l'Ouest​</a> situé dans le golfe de Guinée. Avec plus de 190 millions d'habitants en 2017, le Nigeria est le pays le plus peuplé d'Afrique et le septième pays du monde par son nombre d'habitants.</p>
		<p>Situé au bord du golfe de Guinée, le Nigeria possède 4 047 km de frontières terrestres, et 853 km de littoral. Il est bordé à l'ouest par le ​<a href="Benin.html">Bénin</a> ​(773 km), à l'est par le Cameroun (1 690 km), au nord par le ​<a href="Niger.html">Niger</a>​ (1 497 km), et par le Tchad au nord-est (84 km).</p>
		<p>Le pays est la première puissance économique du continent africain en 2016, et la 27​<sup>e</sup>​ au niveau mondial (PIB) selon la Banque mondiale. Le poids économique et démographique du Nigeria lui ont valu le surnom de « Géant d'Afrique ». Toutefois, malgré une production de pétrole importante et une économie diversifiée, le pays demeure relativement pauvre, notamment en raison d'une forte corruption. Les dernières élections se sont déroulées en mars 2015, <b><i>Muhammadu Buhari​</i></b> (du ​<i>parti All Progressives Congress</i>) succédant à ​<i><b>Goodluck Jonathan</b></i> (du <i>Parti démocratique populaire</i>).</p>
		<p>Depuis 1991, la capitale du Nigeria est la ville nouvelle d'Abuja. Le pays fait partie de la <a href="https://fr.wikipedia.org/wiki/Communaut%C3%A9_%C3%A9conomique_des_%C3%89tats_de_l%27Afrique_de_l%27Ouest" style="color:darkorchid">Communauté économique des États de l'Afrique de l'Ouest</a>​(CEDEAO). Ses habitants sont les <i>Nigérians</i>.</p>
		<h2>SOMMAIRE</h2>
		<ol style="color: deeppink">
			<li> <a href="#Histoire" style="color: deeppink">Histoire</a></li>
			<li><a href="#Geographie" style="color: deeppink">Géographie</a></li>
		</ol>
		<h2 id="Histoire">Histoire</h2>
		<hr>
		<p>Les ​<b><i>Noks</i></b> sont la civilisation dominante du iii​<sup>e</sup>​ au vi<sup>​e</sup>​ siècle, elle diffuse vers les régions d'​<b><i>Ife</i></b> et du <b><i>​Benin</i></b>. Du vii​<sup>e</sup>​ au xi​<sup>e</sup>​ siècle : installation des civilisations ​<b><i>Haoussa</i></b>​ au nord du pays, et <b><i>Yoruba</i></b> au sud-ouest. L'empire du Kanem (jusqu'au xiv​e​ siècle), puis du ​<b>Kanem-Bornou</b>​ (à son apogée au xvi<sup>​e</sup>​ siècle) auprès du lac Tchad a dominé le nord du Nigeria pendant plus de 600 ans, prospérant sur leur position de terminal pour les échanges nord-sud entre les ​<i>berbères</i> d'Afrique du nord et les peuples des régions forestières. Au début du xix<sup>​e</sup>​ siècle, Usman dan Fodio a ramené la plupart des régions du nord du pays sous le contrôle d'un empire islamique dirigé depuis ​<i>Sokoto</i>.</p>
		<p>Les royaumes d'<i><b>​Oyo</b></i> au sud-ouest et au sud-est du Benin ont conçu des systèmes politiques élaborés au cours du xv​<sup>e​</sup> au xvii​<sup>e​</sup> siècle. Les régions d'Ife et du Benin sont aussi connues pour leurs productions artistiques en ivoire, bois, bronze et cuivre. En 1486, les Portugais établissent des contacts avec le royaume du Benin.</p>
		<p>En 1553, les Anglais détruisent les vaisseaux portugais et du xvii​<sup>e</sup>​ au xix<sup>​e</sup>​ siècle les marchands européens établissent des ports côtiers pour le florissant trafic d'esclaves en direction des Amériques. Ce commerce a été remplacé par celui des matières premières au cours du xix​<sup>e</sup> siècle.</p>
		<p>Le gouvernement du Royaume-Uni établit un statut légal pour la Compagnie royale du Niger en 1886. En 1900, ce territoire est découpé en plusieurs protectorats, et devient une colonie en 1914. En réponse au nationalisme montant après la Seconde Guerre mondiale, les Britanniques dotent le pays d'un gouvernement représentatif en 1951 puis d'une constitution fédérale en 1954.</p>
		<p>En 1958, ​<i><b>Taiwo Akinkunmi</b></i> compose le drapeau nigérian.</p>
		<p>Le Nigeria obtient son indépendance totale en 1960. Le pays est alors divisé en trois régions disposant d'une large autonomie.</p>
		<p>La première constitution républicaine de 1963 laisse le pays dans le <i>​Commonwealth</i>. En 1966, un coup d'État fomenté par différents groupes militaires amène au pouvoir le général Ironsi, d'origine Igbo, qui est assassiné quelques mois plus tard. Les meneurs de ce nouveau coup d'État agrandissent le pouvoir du gouvernement fédéral et changent la subdivision du pays qui est désormais constitué de douze États. Les Igbos, ethnie majoritaire de l'est du pays, sont alors victimes de représailles raciales sanglantes qui aboutissent en 1967 à la sécession de la république du Biafra. S'ensuit une terrible guerre qui s'achève par une capitulation des indépendantistes le 12 janvier 1970.</p>
		<p>En 1975, un coup d'État, sans effusion de sang, amène ​<i><b>Murtala Ramat Mohammed</b></i> au pouvoir. Il promet un retour rapide à la démocratie, mais il est tué dans un coup d'État avorté et est remplacé par son second ​<i><b>Olusegun Obasanjo</b></i>. Une nouvelle constitution est établie en 1977 et les premières élections arrivent en 1979, gagnées par ​<i><b>Shehu Shagari</b></i>.</p>
		<p>Un nouveau coup d'État en 1983 replonge le pays sous la dictature du conseil militaire suprême. En 1993, après des élections annulées par le gouvernement militaire, le général ​<i><b>Sani Abacha</b></i> arrive à la tête de l'État. À sa mort soudaine en 1998, <i><b>​Abdulsalami Abubakar​</b></i> prend le pouvoir et rétablit la constitution de 1979. En 1999, les premières élections démocratiques depuis 16 ans sont gagnées par Olusegun Obasanjo, qui est réélu lors des turbulentes élections de 2003. En 2007, des élections une nouvelle fois agitées amènent au pouvoir le successeur désigné d'Olusegun Obasanjo : ​<i><b>Umaru Yar'Adua.</b></i></p>
		<p>Umaru Yar'Adua décède le 5 mai 2010 des suites de maladie. ​<i><b>Goodluck Jonathan</b></i>​ lui succède officiellement le 6 mai 2010. L'Assemblée nationale approuve le 18 mai 2010 la nomination de <i><b>Namadi Sambo​</b></i> comme vice-président du Nigeria.</p>
		<h2 id="Geographie">Géographie</h2>
		<hr>
		<center><img src="Nigeria/Zuma_rock.jpg" style="height: 180px"><p style="font-size: 13px">Le Zuma Rock près de Suleja</p></center>
		<p>Situé au bord du golfe de Guinée, le Nigeria possède 4 047 km de frontières terrestres, et 853 km de littoral. Il est bordé à l'ouest par le ​<a href="Benin.html">Bénin​</a> (773 km), à l'est par le Cameroun (1 690 km), au nord par le ​<a href="Niger​.html">Niger</a>​ (1 497 km), et par le Tchad au nord-est (84 km).</p>
		<p>Le pays se divise en une moitié sud au climat équatorial où se situe la majorité des villes importantes, une partie centrale composée de régions de savane et de plateaux, une partie est où l'on trouve le point culminant, le mont Chappal Waddi (2 419 m), et une partie nord au climat aride puisqu'on se trouve dans le ​<i>Sahel</i>, en bordure du désert du <i>​Sahara</i>.</p>
		<p>Le sous-sol est riche en ressources naturelles parmi lesquelles le pétrole et le gaz constituent la principale source de revenu du pays. Le pays est le premier producteur d'or noir d'Afrique. Le Nigeria produit également un certain nombre de métaux (étain, fer, plomb, zinc…) ainsi que du charbon.</p>
