<h1>NIGER</h1>
		<img src="Niger/flag-niger.png" style="height: 200px">
		<p>Le <b>​Niger</b>​, en forme longue la <b>​république du Niger</b>​, est un pays d'Afrique de l'Ouest steppique, situé entre l'Algérie, le <a href="Benin.html">​Bénin</a>​, <a href="​Burkina-Faso.html">le ​Burkina Faso​</a>, le Tchad, la Libye, le Mali et le <a href="Nigeria.html">​Nigeria</a>​. La capitale est <b>​Niamey​</b>. Les habitants sont des ​<b><i>Nigériens</i></b>. Le pays est ​<a href="https://fr.wikipedia.org/wiki/Multiethnique" style="color: darkslateblue">multiethnique​</a> et constitue une terre de contact entre l'Afrique subsaharienne et l'Afrique du Nord. Le Niger fait partie de la <a href="https://fr.wikipedia.org/wiki/Communaut%C3%A9_%C3%A9conomique_des_%C3%89tats_de_l%27Afrique_de_l%27Ouest" style="color:darkslateblue">Communauté économique des États de l'Afrique de l'Ouest​</a> (CEDEAO).</p>
		<p>Les plus importantes ressources naturelles du Niger sont l'or, le fer, le charbon, l'uranium et le pétrole. En 2016, le Programme des Nations unies pour le développement a considéré le Niger comme l'un des pays les plus émergents dans son rapport annuel.</p>
		<h2>SOMMAIRE</h2>
		<ol style="color: deeppink">
			<li><a href="#Histoire" style="color: deeppink">Histoire</a></li>
			<li><a href="#Politique" style="color: deeppink">Politique</a></li>
			<li><a href="#Subdivisions" style="color: deeppink">Subdivisions</a></li>
			<li><a href="#Geographie" style="color: deeppink">Géographie</a></li>
			<ol>
				<li><a href="#Environnementetagriculture" style="color: deeppink">Environnement et agriculture</a></li>
			</ol>
			<li><a href="#Demographie" style="color: deeppink">Démographie</a></li>
			<ol>
				<li><a href="#Situationdesfemmes" style="color: deeppink">Situation des femmes</a></li>
			</ol>
			<li><a href="#Economie" style="color: deeppink">Economie</a></li>
		</ol>
		<h2 id="Histoire">Histoire</h2>
		<hr>
		<p>L'occupation humaine de la région remonte au moins au VIII​<sup>e</sup>​ millénaire av. J.-C. (céramiques du massif de l'Aïr) ; un cimetière du III​<sup>e</sup>​ millénaire av. J.-C. a été découvert en 2005 dans le désert du Ténéré. Au I<sup>​er</sup>​ millénaire av. J.-C., les Berbères se seraient introduits par une des routes transsahariennes, refoulant vers le sud les populations sédentaires ou se métissant avec elles.</p>
		<p>Au vii<sup>​e</sup>​ siècle, l'Empire songhaï se constitue. La capitale de l'Empire est, à partir du x<sup>​e</sup>​ siècle, Gao. La région devient musulmane au début du xi​<sup>e</sup>​ siècle, lorsque les rois de Moukia se convertissent à l'islam. En 1591, l'Empire est défait par les Saadiens. Entre les xvii​<sup>e​</sup> et xix<sup>​e</sup> siècles, les Touaregs et les Peuls contrôlent une partie du pays et, bien avant cette date, les Haoussas dominent sa partie sud. La zone est conquise par les Français en 1890, la frontière franco-anglaise (ligne Say-Barroua), est reportée plus au nord par la convention de Paris du 14 juin 1898. Trois missions françaises (Fourau-Lamy au Sahara, Voulet-Chanoine puis Joalland-Meynier par l'ouest, Gentil à partir du Congo), lancées cette même année, se rejoignirent en avril 1900 à Kousseri et y détruisirent les forces du chef Rabah, unissant l'ensemble des possessions françaises d'Afrique. Territoire militaire depuis 1900, pacifié depuis 1920, le Niger est érigé en colonie le 13 octobre 1922, à l'intérieur de l'Afrique-Occidentale française ; devenue membre de la Communauté française en décembre 1958, la république est indépendante depuis le 3 août 1960.</p>
		<h2 id="Politique">Politique</h2>
		<hr>
		<p>Ancienne colonie française devenue État indépendant en 1960, le Niger est gouverné par le président Hamani Diori dans un système de parti civil unique.</p>
		<p>En 1974, une sécheresse dévastatrice et des accusations de corruption aboutissent à un coup d'État mené par le lieutenant-colonel Seyni Kountché. Ce dernier dirige le pays avec un petit groupe de militaires jusqu'à sa mort en 1987.</p>
		<p>Son chef d'état-major, le colonel Ali Saibou, lui succède, relâche certains prisonniers politiques, libéralise la législation et la politique nigérienne et promulgue une nouvelle Constitution. Toutefois, les efforts du président Ali Saibou en faveur de ces réformes échouent face aux demandes de la société civile en faveur de l'institution d'un régime démocratique et multipartite, le régime finit par les accepter à la fin 1990. De nouveaux partis et mouvements civiques font leur apparition et une conférence nationale pour la paix civile est réunie en juillet 1991 pour préparer la transition vers des élections libres et transparentes. Ce débat contradictoire permet l'émergence d'un consensus pour la formation d'un gouvernement de transition en novembre 1991 dirigé par Amadou Cheiffou, gouvernement qui se maintient jusqu'à la fondation des institutions de la Troisième République.</p>
		<p>En avril 1993 Mahamane Ousmane devient président après une élection considérée comme démocratique. Si l'économie va en se dégradant, certaines réalisations sont à souligner, comme l'organisation réussie d'un référendum constitutionnel, l'adoption d'un code électoral ainsi que celle d'un code rural et enfin la tenue d'une série d'élections libres, dans un climat pacifié et sur tout le territoire. La liberté de la presse permet alors l'éclosion de nombreux journaux indépendants.</p>
		<p>Les résultats des élections législatives de 1995 aboutissent à la cohabitation entre le président et son rival, ancien Premier ministre, et ​<i>in fine</i>​ à la paralysie gouvernementale. Le colonel Ibrahim Baré Maïnassara met en place le Conseil de salut national en 1996 et prend la tête d'une transition de six mois pour rédiger la constitution pour une Quatrième République. Baré organise l'élection présidentielle en juillet de la même année mais, alors que le processus de vote est en cours, remplace les membres de la Commission électorale et se fait déclarer vainqueur par cette dernière. Les élections législatives truquées de novembre suivant lui donnent une majorité de 57 % des sièges. Ce coup de force éloigne les donateurs étrangers, poussant le président Baré à rechercher l'aide de la Libye pour soutenir l'économie nigérienne. Parallèlement, on assiste à des violations répétées des droits de l'homme les plus élémentaires, les dirigeants de l'opposition sont arrêtés pendant que des journalistes sont souvent arrêtés et déportés par une milice officieuse composée de policiers et de militaires. Enfin, les bureaux des médias indépendants sont pillés et brûlés.</p>
		<p>Cependant, il reste alors un point positif de ces journées de conférence nationale de 1991. L'initiative entamée pour rechercher la paix avec la première rébellion touarègue et touboue permet la signature d'un accord de paix en avril 1995. Les Touaregs revendiquent une plus grande autonomie sur leur territoire, ainsi que des retombées économiques des activités minières qui s'effectuent sur leur territoire. Ils réclament des emplois dans ces mines par exemple. Il s'agit également de revendications sociales et politiques. Les Touaregs dénoncent leur marginalisation et demandent une plus grande autonomie au pouvoir en place. Le gouvernement nigérien répondit par les armes, via l'armée nationale.</p>
		<p>Le 9 avril 1999, Baré est tué dans un coup d'État mené par le commandant ​<b>Daouda Malam Wanké</b>​, qui établit un régime de transition pour un retour à la démocratie. Lors des élections législatives et présidentielle d'octobre et novembre 1999, la coalition du ​<i><b>Mouvement national pour la société du développement</b></i>​ (MNSD) et de la ​<i><b>Convention démocratique et sociale</b></i> (CDS), menée par ​<b>Mamadou Tandja</b>​, gagne les élections.</p>
		<p>La nouvelle Constitution du Niger est approuvée en juillet 1999. Elle restaure le régime semi-présidentiel de la Constitution de 1992 où le président est élu au suffrage universel pour 5 ans et nomme le Premier ministre avec lequel il partage le pouvoir exécutif. L'Assemblée nationale, pour suivre l'évolution démographique du pays, voit ses effectifs monter à 171 députés, également élus pour 5 ans selon un scrutin majoritaire.</p>
		<p>Le nouveau pouvoir doit affronter une mutinerie militaire en août 2002 dans le Sud-Est du pays. L'état d'urgence est déclaré mais les mutins sont rapidement ramenés dans leurs casernes ou arrêtés par les troupes fidèles au gouvernement.</p>
        <center><img src="Niger/mahamadou_issoufou.jpg" style="height: 300px"><p style="font-size: 13px">Mahamadou Issoufou, actuel président du Niger. </p></center>
        <center><img src="Niger/lieutenant_colonel_of_army_of_niger.jpg" style="height: 300px"><p style="font-size: 13px">Un lieutenant-colonel des Forces armées du Niger.</p></center>
        <p>La législature élue en décembre 2004 accueille sept partis politiques différents. <b>​Mamadou Tandja</b>​ est réélu président en décembre 2004 et choisit de nouveau ​<b>Hama Amadou</b>​ comme Premier ministre. Mahamane Ousmane, à la tête de la CDS, est réélu Président de l'Assemblée nationale par ses pairs.</p>
        <p>En juin 2007, Seyni Oumarou est nommé Premier ministre après une motion de censure qui renverse le gouvernement Hama Amadou. Mais de 2007 à 2008, une seconde rébellion touarègue a lieu au nord du Niger, aggravant les perspectives économiques du pays et refermant à nouveau la page des progrès politiques.</p>
        <p>Le​ <i>4 août 2009</i>, le président Mamadou Tandja réussit son coup de force lors du référendum constitutionnel décrété illégal par la Cour constitutionnelle et contesté par l'opposition politique. Ce référendum vise à autoriser le remplacement de la constitution nigérienne. Les deux grands changements qu'il engendre sont la non limitation du nombre de mandats présidentiels et le passage d'un régime semi-présidentiel à un régime présidentiel. Mamadou Tandja bénéficie d'une extension exceptionnelle de son mandat de 3 ans pour « achever les chantiers entrepris ». La tenue du référendum est précédée et suivie de grandes manifestations et contestations.</p>
        <p>Le ​<i>18 février 2010</i>, un coup d'État est organisé dans la capitale Niamey aux abords du palais présidentiel. Les insurgés placent le président en état d'arrestation et un Conseil suprême pour la restauration de la démocratie (CSRD) est mis en place, sous la présidence de ​<b>Salou Djibo</b>​, chef d'escadron de l'armée nigérienne. Le lundi 1​er​ mars 2010, le Conseil suprême pour la restauration de la démocratie présente un gouvernement de 20 membres parmi lesquels figurent cinq militaires. Mahamadou Danda est nommé Premier ministre. La Septième République est proclamée par le chef de la transition le 25 novembre 2010.</p>
        <p>Après des élections reconnues libres et transparentes par les différents observateurs, en mars et avril 2011, Mahamadou Issoufou a prêté serment le jeudi 7 avril 2011. Il nomme le même jour <b>Brigi Rafini</b>​ au poste de Premier ministre.</p>
        <h2 id="Subdivisions">Subdivisions</h2>
        <hr>
        <p>Le Niger est divisé en 8 régions : <b>​Agadez</b>​, ​<b>​Diffa</b>​, <b>​​Dosso</b>​, <b>​​Maradi​</b>, <b>​​Niamey​</b>, ​<b>​Tahoua​</b>, ​<b>​Tillaberi​</b>, <b>​Zinder​</b>. Chaque région porte le nom de sa capitale.</p>
        <p>Les régions sont divisées en 63 départements depuis 2012 ayant à leur tête des préfets.</p>
        <p>La capitale, ​<b>​Niamey</b>​, est une communauté urbaine distincte. La ville de Niamey est composée de 5 communes.</p>
        <h2 id="Geographie">Géographie</h2>
        <p>La situation géographique du Niger fait de lui un carrefour d'échanges entre l'Afrique du Nord et l'Afrique au sud du Sahara. Situé en Afrique occidentale entre les parallèles 11°37 et 23°33 de latitude nord d'une part, et les méridiens 16° de longitude est et 0°10 de longitude ouest d'autre part, le Niger s'étend sur 1 267 000 km<sup>​2</sup>​. Il est le plus vaste des pays de l'Afrique occidentale et se classe 6<sup>​e</sup>​ à l'échelle continentale (après l'Algérie, la République démocratique du Congo, le Soudan, la Libye et le Tchad). La plupart des villes importantes sont concentrées dans le Sud du pays, le Nord étant aride ou hyper-aride (Sahara). </p>
        <h3 id="EnvironnementetAgriculture">Environnement et Agriculture</h3>
        <hr>
        <p>Le territoire du Niger est constitué à 80 % du ​<b>Sahara</b>​ et du <b>​Sahel</b>​. Seule une bande au sud du pays est verte. L'accès à l'eau est un problème pour une grande partie de la population, même si des châteaux d'eau arrivent petit à petit dans les villes. </p>
        <p>Le désert progresse de 200 000 hectares chaque année. Les programmes gouvernementaux de <i>reforestation</i>​ se heurtent aux fréquentes ​<i>sécheresses</i>​ et à la demande croissante en bois et en terres agricoles. Depuis 1990, la forêt a perdu un tiers de sa surface et ne couvre plus que 1 % du pays. 8 % seulement du territoire reçoit plus de 400 millimètres de pluie par an qui autorise une agriculture satisfaisante. En 2015, le pays est en situation de pénurie alimentaire structurelle.</p>
        <p>Grâce au collectif de régénération naturelle gérée par les agriculteurs, plus de 5 millions d’hectares de terres au Niger présentent aujourd’hui des signes de régénération de la végétation en 2005 par rapport aux années 1970. La dégradation des terres a été nettement réduite, l’érosion diminuée, la fertilité augmentée et la productivité agricole améliorée de façon spectaculaire.</p>
        <p>Certains animaux, comme les <b><i>​éléphants</i></b>, les ​<b><i>lions</i></b> et les <b><i>​girafes</i></b>, sont en danger de disparition en raison de la destruction de la forêt et du braconnage. Le dernier troupeau de girafes en liberté de toute l'Afrique de l'Ouest évolue dans les environs du village de Kouré, à 60 km de la capitale Niamey. D'autre part, un parc portant le nom de « <a href="https://fr.wikipedia.org/wiki/Parc_national_du_W_du_Niger">​parc national du W du Niger​ </a>​» (à cause des sinuosités du fleuve Niger à cet endroit) se trouve sur le territoire de trois pays : le Niger, le <a href="​Bénin​.html">​Bénin​</a> et le <a href="​Burkina-Faso.html">​​Burkina Faso​</a>. Dans le fleuve <a href="Niger.html">​​Niger</a>​, les hippopotames sont protégés et se multiplient au point de devenir menaçants pour les populations locales. À la tombée de la nuit, il n'est pas rare qu'ils viennent saccager les cultures du bord du fleuve</p>
        <h2 id="Demographie">Démographie</h2>
        <hr>
        <p>Forte de 3 millions d’habitants en 1960, la population du Niger est estimée à 20 millions d'habitants en 2018.</p>
        <p>Les différentes ethnies sont :</p>
        <ul>
        	<li>les ​<b><i>Haoussas</i></b> (55,4 % de la population), qui vivent dans le Centre et l'Est du pays avec une aire culturelle largement étendue au ​<a href="Nigeria.html">Nigeria</a>​ ;</li>
        	<li>les <b><i>​Zarmas​</i></b> (18,2 %) et les ​Songhaïs​ (4,0 %) qui occupent l'Ouest du pays ;</li>
        	<li>les ​<b><i>Touaregs​</i></b> (11 %), ​Toubous​ (0,1 %) ;</li>
        	<li>les ​<b><i>Peuls​</i></b> (10 %) répartis sur tout le territoire avec une forte concentration dans la région de Tillabéri</li>
        	<li>les ​<b><i>Kanouris</i></b>​ (4,2 %) et les ​Boudoumas​ dans l'Extrême-Est ;</li>
        	<li>les ​<b><i>Gourmantchés</i></b>​ (0,3 %) dans le Sud-Ouest du pays.</li>
        	<li>les ​<b><i>Arabes</i></b>​ 0,04% de la population, répartis majoritairement dans le Nord du pays et dans la capitale.</li>
        </ul>
        <h3 id="Situationdesfemmes">Situation des femmes</h3>
        <hr>
        <p>Le pays possède le taux de fécondité le plus élevé au monde avec 7,6 enfants par femme en moyenne. En 2015, une personne sur deux a moins de 15 ans. Selon le Fonds des Nations unies pour l'enfance (Unicef), 30 % des filles sont mariées avant l'âge de 15 ans et 75 % avant 18 ans. Ces mariages ont souvent pour conséquence d'interrompre la scolarisation des filles. La charge de travail journalière de la femme rurale est de 16 à 18 heures et ne lui donne que bien peu de temps pour ses enfants. Près de 60 % des femmes pensent que, pour au moins une des raisons citées, il est justifié qu’un homme batte sa femme.</p>
        <p>Cette démographie galopante s'explique autant par le poids des traditions patriarcales que de la religion, mais aussi en la croyance que les enfants fournissent une main-d'œuvre agricole gratuite. Cependant, sous le coup de la pression démographique et du réchauffement climatique, les terres cultivables se font de plus en plus rares et ont moins de rendement. Alors que la population risque encore de doubler d'ici deux décennies, le gouvernement lance à la fin des années 2010 des programmes de sensibilisation à la contraception à destination des femmes.</p>
        <h2 id="Economie">Economie</h2>
        <hr>
        <p>Le Niger est membre de l'Union économique et monétaire ouest-africaine.</p>
        <p>Dès décembre 2004, l'ONU avertit d'une probable famine pour 2005, provoquée par la <i>sécheresse​</i> et les invasions de <i>​criquets</i>. Environ 33 % de la population nigérienne (3,5 millions de personnes) serait affectée par la pénurie alimentaire. Fin 2005 et sans l'aide financière demandée par l'ONU, 2,4 millions de Nigériens ont été touchés.</p>
        <p>Les exportations vers la France de l'uranium des mines d'Arlit ont longtemps constitué une part importante du revenu extérieur du pays. En janvier 2009, le gouvernement du Niger et la présidente du directoire d'Orano signaient une convention minière stratégique accordant au groupe nucléaire français un permis d'exploitation sur le gisement d'Imouraren, présentée par Areva comme la « mine d'uranium la plus importante de toute l'Afrique et la deuxième du monde » derrière celle de ​<b><i>McArthur River​</i></b> au Canada. Quand la mine tournera à plein régime, le Niger deviendra alors le deuxième producteur mondial d'uranium derrière le Canada.</p>
        <p>Les mines de charbon de la région de ​<i>Tchirozérine</i> sont exploitées à ciel ouvert.</p>
		<p>Le Niger dispose de plusieurs réserves de pétrole. La région d'Agadez, Zinder, Tahoua et Diffa regorge le pétrole. Selon l'U.S. Energy Information Administration (EIA), la production a démarré fin 2011. En 2012, la production était de 20 000 barils par jour. En 2014 elle devrait atteindre 80 000 barils par jour.</p>
		<p>Par manque d'infrastructures de qualité et de masse, le tourisme est peu développé. Certaines routes « goudronnées » ne sont pas entretenues (accidents fréquents). Il existe une voie ferrée en cours de réalisation et seulement deux aéroports internationaux à Niamey et à Agadez. Seule la partie nord est un peu ouverte aux touristes recherchant le désert. Bien que le Niger soit l'un des plus importants producteurs d'uranium au monde, il figure dans les derniers de la planète en matière de développement humain (source ONU). L'oignon nigérien alimente mieux le budget que l'uranium, qui, au surplus, contamine la population par la fréquence de plusieurs maladies.</p>
		<p>En plus de l'uranium, des sociétés étrangères ont été autorisées à prospecter d'autres ressources dans le désert, comme le Canadien SEMAFO qui exploite une mine d'or. Depuis la fin des années 1990, les « compagnies juniors » canadiennes, qui ont investi dans plus de 8 000 propriétés minières, dans plus de 100 pays, pour la plupart encore à l'état de projet multiplient les contrats avec des pays africains. La pauvreté minant le pays et le gouvernement refusant d'investir pleinement dans les zones sous le contrôle des Touaregs, les nomades se sont révoltés.</p>
		<p>Le PIB du Niger a connu une augmentation de 2 % en 2009. Il était de 10,45 milliards de dollar US à cette même date. L'agriculture occupait 39 %, le secteur tertiaire 44 % et le secteur industriel 17 % du PIB en 2001. L'agriculture est aussi le secteur économique qui mobilise le plus de population (90 %). Le PIB par habitant est de 1 200 dollars US.</p>
